# Generated by Django 5.1.3 on 2024-11-30 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 11, 30, 11, 0, 9, 953658, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
