# Generated by Django 5.1.3 on 2024-11-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
